### ISSUE TITLE
Add a slider for images in product page.

### ISSUE THREAD

**Issue by victorchrollo14** [victorchrollo14/mernEcommerce#59]
Add a slider in products page, in the below file to slide through images.
`client/src/pages/product/leftSection.jsx`

**Comment by Sky-De** [comment]
@victorchrollo14 hi there, i would like to work on this 
please assign this to me 
thanks

**Comment by victorchrollo14** [comment]
Yeah sure, you can fix that up

**Comment by Sky-De** [comment]
@victorchrollo14 please assign this to me then i will be able keep track of this issue , because i'm working on couple of diffrent open source projects, and only way for me to access them very fast is my assigned issues page
as soon as i get assignment i will start working on this 
it will take 1 or 2 hours
another thing, is it ok with you if i use slick-carousel for this implementation ?
https://www.npmjs.com/package/slick-carousel

**Comment by victorchrollo14** [comment]
Done.
